version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    networks:
      - watchgroup
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - watchgroup

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - watchgroup
    depends_on:
      - db

networks:
  watchgroup:
    driver: bridge
